version: '3.1'

services:

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tacoscloud
      MYSQL_USER: tacoscloud
      MYSQL_PASSWORD: tacoscloud
    ports:
      - 3306:3306
